services:
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      TZ: Asia/Tokyo
    volumes:
      # - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/nginx_subdomain.conf:/etc/nginx/nginx.conf
      - /vagrant/oreore/daieihawks.crt:/daieihawks.crt
      - /vagrant/oreore/daieihawks.key:/daieihawks.key
    ports:
      - "443:443"
    depends_on:
      - redmine
      - gitea
    restart: unless-stopped

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_USER: admin
      TZ: Asia/Tokyo
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale-provider=icu --icu-locale=ja-JP"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
      - /storage/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redmine:
    image: redmine:latest
    container_name: redmine
    environment:
      REDMINE_DB_POSTGRES: postgresql
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: admin
      REDMINE_DB_PASSWORD: passw0rd
      TZ: Asia/Tokyo
    volumes:
      - ./redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
      - /storage/redmine/files:/usr/src/redmine/files
    depends_on:
      - postgresql
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      # - GITEA__server__ROOT_URL=https://192.168.0.99/gitea
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgresql
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=admin
      - GITEA__database__PASSWD=passw0rd
      - TZ=Asia/Tokyo
    volumes:
      - /storage/gitea/data:/data
    depends_on:
      - postgresql
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"
    restart: unless-stopped
